#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as an error, and fail on error in any pipeline
set -euo pipefail

eval "$(.python/Miniconda3/bin/conda shell.bash hook)"
conda activate .python/venv/
python .python/align_pip.py
